
base:
  log_level: INFO
  random_state: 42

get_training_dataset:
  training_dataset: data/input/nba_training_dataset.csv

data_split:
  split_ratio: 0.20
  group_cv_variable: id

dummy_classifier:
  target_variable: results

initial_multiple_models_training:
  random_state: 21
  cross_validation_n_splits: 3

train:
  top_3_models: data/processed/top_3_models.csv
  model_name: Extreme Gradient Boosting # Random Forest Classifier
  param_grid:
    max_depth: 3
    n_estimators: 1000
    # max_features: 0.4
    learning_rate: 0.05
  # estimator_configs:
  #   - name: Random Forest Classifier
  #     param_grid:
  #       max_depth: 5
  #       n_estimators: 1000
  #       max_features: 0.5
  #   - name: Extreme Gradient Boosting
  #     param_grid:
  #       max_depth: 4
  #       n_estimators: 100
  #       learning_rate: 0.01
  cross_validation_n_splits: 10
  scoring_metric: accuracy