
base:
  log_level: INFO
  random_state: 42

get_training_dataset:
  training_dataset: data/input/nba_training_dataset.csv

data_split:
  split_ratio: 0.20
  group_cv_variable: id

dummy_classifier:
  target_variable: results

initial_multiple_models_training:
  random_state: 21
  cross_validation_n_splits: 10

feature_selection:
  list_features_to_select:
    - results
    - id
    - id_season
    - tm
    - opp
    #- game_nb
    - before_average_W_ratio
    - before_average_W_ratio_opp
    - extdom_ext
    - before_ratio_win_ext
    - before_ratio_win_dom
    - rest
    - before_average_pts_tm
    - before_average_pts_opp
    # - before_streak_w_l

train:
  top_3_models: data/processed/top_3_models.csv
  model_name: Extreme Gradient Boosting
  cross_validation_n_splits: 10
  scoring_metric: accuracy
  param_grid:
    max_depth: 2
    n_estimators: 750
    learning_rate: 0.05

evaluate:
  metrics_path: data/reports/metrics.json
  # regression_plot: regression_plot.png
  shap_beeswarm_image: shap_beeswarm.png
  shap_plot_bar_image: shap_plot_bar.png
  # regression_plot_data: regression_plot_data.csv