
base:
  log_level: INFO
  random_state: 42

get_training_dataset:
  training_dataset: data/input/nba_games_training_dataset_final.csv

data_process:
  training_dataset_processed: data/processed/nba_training_dataset_processed.csv

data_split:
  split_ratio: 0.33
  group_cv_variable: id

dummy_classifier:
  target_variable: results

initial_multiple_models_training:
  random_state: 21
  cross_validation_n_splits: 5

feature_selection:
  method: automatic # manual
  list_nb_feature_to_select: "5/7/9"
  rfe_step: 10
  cross_validation_n_splits: 5
  random_state: 21
  features_to_force:
  list_manual_features_to_select:
    - game_nb
    - before_average_W_ratio
    - before_average_W_ratio_opp
    - extdom_ext
    - rest
    - before_average_pts_tm
    - before_average_pts_opp
    - before_average_pts_tm_opp
    - before_average_pts_opp_opp

train:
  top_3_models: data/processed/top_3_models.csv
  model_name: Extreme Gradient Boosting
  cross_validation_n_splits: 5
  scoring_metric: accuracy
  param_grid:
    max_depth: 5
    n_estimators: 750
    learning_rate: 0.01

evaluate:
  metrics_path: data/reports/metrics.json
  shap_beeswarm_image: shap_beeswarm.png
  shap_plot_bar_image: shap_plot_bar.png