name: CML
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --no-root
      - uses: iterative/setup-cml@v2
      - name: Train model
        run: |
          poetry run dvc repro
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Metrics Report" >> report.md
          git fetch --prune
          poetry run dvc metrics diff main --md >> report.md

          echo "## Training Plots" >> report.md
          poetry run dvc plots --show-vega >> vega.json
          cmd vl2png vega.json > plot.png
          echo '![](./plot.png "Training Loss")' >> report.md

          echo "## Plots" >> report.md
          echo "![](./data/reports/ConfusionMatrix.png)" >> report.md

          cml comment create report.md