name: CML
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      # - uses: actions/checkout@v4
      #   with:
      #     ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --no-root
      - uses: iterative/setup-cml@v2
      - name: Activate env
        run: poetry shell
      - name: Train model
        run: |
          poetry shell
          dvc repro
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "\`\`\`" > report.md
          echo "![](./data/reports/ConfusionMatrix.png)" >> report.md
          cml comment create report.md